### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by SwiftsNamesake** [plredmond/GPipe-GLFW#17]
This package is currently unusable with the latest version of GHC and base.

**Comment by TiloWiklund** [comment]
It has overly conservative upper bounds on base and transformers, relaxing them makes everything compile in GHC 8.0.1 and at least basic examples work.

**Comment by plredmond** [comment]
Thanks for the heads up! I just started a new job and have been lacking a
development environment on my pc. Feel free to submit a pr if you are
inclined, otherwise I'll probably resume development on this in November. :)

**Comment by SwiftsNamesake** [comment]
You're very welcome, and thanks for this library.

I created a fork with relaxed constraints shortly after opening this issue. I suppose I could submit a pull request if you have time to review it. I also intend to make a few other additions (such as completing the event bindings).

**Comment by plredmond** [comment]
If you can submit a pr with just the relaxed constraints, that'd be great.
Thank you!

When you like wuere you are with the event bindings, I would greatly
appreciate seeing how you chose to implement them if you're inclined to
share.

Thank tobias for gpipe! This is just an aux library. :)

On Wed, Oct 26, 2016 at 06:51 Jonatan <notifications@github.com> wrote:

You're very welcome, and thanks for this library.

I created a fork with relaxed constraints shortly after opening this issue.
I suppose I could submit a pull request if you have time to review it. I
also intend to make a few other additions (such as completing the event
bindings).

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/plredmond/GPipe-GLFW/issues/17#issuecomment-256353465>,
or mute the thread

**Comment by SwiftsNamesake** [comment]
Alright, I will.

While I have your attention, is there a rationale for the slightly unusual directory structure?
Stack-generated projects usually have the `src` directory and `.cabal` file at the top level.

**Comment by plredmond** [comment]
I'm following the directory structure used in [GPipe-Core](https://github.com/tobbebex/GPipe-Core).

**Comment by plredmond** [comment]
Hey! I hacked on this a bit this weekend and merged your changes @SwiftsNamesake! I'm merging in a branch I've been working on and then I'll reupload to hackage/stackage for great good!

**Comment by plredmond** [comment]
The new version is on [hackage](http://hackage.haskell.org/package/GPipe-GLFW), though the docs are broken. Docs were successfully generated on [stackage](https://www.stackage.org/nightly-2016-11-15/package/GPipe-GLFW-1.2.3) though so I'm closing this issue.
